### ISSUE TITLE
求教下该EFI对应的系统版本以及BIOS版本

### ISSUE THREAD

**Issue by lujiaosama** [johnyang007/b460m-martor-wifi#1]
你好, 请问下B460M迫击炮的BIOS版本更新到了1.20了么?以及该EFI 对应的具体系统版本号? 是Catalina 10.X?还是BIG SUR呢?
我的配置和您的非常相近, 主要是显卡不同. 我的是RX560.希望借助您的EFI完成第一次黑苹果的尝试.期望您的解答,谢谢.

**Comment by johnyang007** [comment]
bios版本升级到最新就行，没太大影响。系统版本是最新的正式版10.15.x。还未支持10.16。
