### ISSUE TITLE
b460m-martor-wifi 主板自带的wifi和蓝牙可以用吗？

### ISSUE THREAD

**Issue by jiangzhx** [johnyang007/b460m-martor-wifi#2]
b460m-martor-wifi 主板自带的wifi和蓝牙可以用吗？
是否还需要单独购买？

谢谢

**Comment by johnyang007** [comment]
需要单独购买，无法使用。

**Comment by linai081795** [comment]
可以使用 
但是需要加入kext

**Comment by johnyang007** [comment]
据说使用 https://github.com/OpenIntelWireless/itlwm 可以驱动，但是不完美。
