### ISSUE TITLE
EFI替换

### ISSUE THREAD

**Issue by yiyezhiqiu1024** [johnyang007/b460m-martor-wifi#4]
使用黑果小兵的镜像制作的启动U盘，替换OC/EFI文件，U盘启动不能启动OpenCore，请问是不支持这样替换吗？

**Comment by johnyang007** [comment]
黑果小兵的镜像我用过，其实我一直没整明白他那些分区的逻辑。。最后放弃了，直接照着open core官方文档制作U盘非常简单。
