### ISSUE TITLE
谢谢老板

### ISSUE THREAD

**Issue by lastshrek** [johnyang007/b460m-martor-wifi#5]
8月份就用了您的efi，刚刚直接复制efi直升big sur成功！6666！

**Comment by johnyang007** [comment]
> 8月份就用了您的efi，刚刚直接复制efi直升big sur成功！6666！
🤝

**Comment by lastshrek** [comment]
有个问题，我才发现我的蓝牙可以显示但是搜不到设备，请问有什么办法可以解决嘛？我用的是cs2
