### ISSUE TITLE
WiFi和蓝牙

### ISSUE THREAD

**Issue by MarsWgl** [johnyang007/b460m-martor-wifi#6]
大佬，主板的WiFi和蓝牙能驱动吗？如果用外接的网卡，主板自带的需要禁用吗

**Comment by johnyang007** [comment]
自带的据说是可以驱动的但不完美。有兴趣可以折腾一下。
可以看这里：https://github.com/OpenIntelWireless/itlwm

我是直接买了原生网卡替换掉了自带网卡，经过usb映射后系统自己就认出来了。

**Comment by MarsWgl** [comment]
> 自带的据说是可以驱动的但不完美。有兴趣可以折腾一下。
> 可以看这里：https://github.com/OpenIntelWireless/itlwm
> 
> 我是直接买了原生网卡替换掉了自带网卡，经过usb映射后系统自己就认出来了。

我用了这个驱动，WiFi不是很稳定，用了他的蓝牙驱动，感觉没加载到，固件都加载不出来

**Comment by johnyang007** [comment]
据说dw1560啥的挺稳定的

**Comment by lolo-zhou** [comment]
我USB隐射不成功

ken <notifications@github.com> 于 2020年12月7日周一 09:20写道：

**Comment by johnyang007** [comment]
什么主板，什么网卡？

**Comment by MarsWgl** [comment]
> 据说dw1560啥的挺稳定的

我放弃折腾Intel那个了,买了个fv-t919,现在用着感觉还行

**Comment by johnyang007** [comment]
用着稳定就好，919这块卡也是有口皆碑
